services:
  frontend:
    build:
      context: .
      dockerfile: DockerFileFrontend
    container_name: barbershop-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
