services:
  frontend:
    build:
      context: .
      dockerfile: DockerFileFrontend
    container_name: barbershop-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: DockerFileBackend
    container_name: barbershop-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      database:
        # wait for the database to be healthy before starting the backend
        condition: service_healthy
      valkey:
        condition: service_healthy
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      VALKEY_HOST: ${VALKEY_HOST:-valkey}
      VALKEY_PORT: ${VALKEY_PORT:-6379}
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - app-network

  valkey:
    image: valkey/valkey:8.0-alpine
    container_name: barbershop-valkey
    ports:
      - "6379:6379"
    volumes:
      - barbershop-valkey_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  database:
    image: mysql:8.0
    container_name: barbershop-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - barbershop-with-roles_db_data:/var/lib/mysql
    #      - ./backend/src/main/resources/data/barbershop-with-roles_dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  barbershop-with-roles_db_data:
  barbershop-valkey_data:
